openapi: 3.0.0
info:
  title: OpenAPI schema
  version: 0.0.1
servers:
  - url: http://localhost
components:
  schemas:
    Apple:
      type: object
      required:
        - color
      properties:
        color:
          type: integer
          enum:
            - 1
            - 2
          nullable: true
          x-enum-varnames:
            - Red
            - Yellow

paths:
  /apple:
    get:
      operationId: getApple
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Apple'