/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI schema
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Apple
 */
export interface Apple {
    /**
     * 
     * @type {number}
     * @memberof Apple
     */
    color: AppleColorEnum;
}


/**
 * @export
 */
export const AppleColorEnum = {
    Red: 1,
    Yellow: 2
} as const;
export type AppleColorEnum = typeof AppleColorEnum[keyof typeof AppleColorEnum];


export function AppleFromJSON(json: any): Apple {
    return AppleFromJSONTyped(json, false);
}

export function AppleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Apple {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'color': json['color'],
    };
}

export function AppleToJSON(value?: Apple | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'color': value.color,
    };
}

